neo_toolbar.neo_toolbar.*:
  type: config_entity
  label: Toolbar
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    weight:
      type: integer
      label: 'Weight'
    visibility:
      type: sequence
      label: 'Visibility Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Visibility Condition'

neo_toolbar.neo_toolbar_item.*:
  type: config_entity
  label: Neo Toolbar Item
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    toolbar:
      type: string
      label: 'Toolbar'
    region:
      type: string
      label: 'Region'
    plugin:
      type: string
      label: 'Plugin'
    weight:
      type: integer
      label: 'Weight'
    settings:
      type: neo_toolbar_item.settings.[%parent.plugin]
      nullable: true
    visibility:
      type: sequence
      label: 'Visibility Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Visibility Condition'

neo_toolbar_item.settings.*:
  type: neo_toolbar_item_settings

neo_toolbar_item_settings:
  type: mapping
  label: 'Neo toolbar item settings'
  mapping:
    id:
      type: string
      label: 'ID'
    provider:
      type: string
      label: 'Provider'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        type: string

neo_toolbar_item_link_settings:
  type: neo_toolbar_item_settings
  label: 'Neo toolbar link item settings'
  mapping:
    url:
      type: string
      label: URL
    token:
      type: mapping
      label: Token
      mapping:
        tokens:
          type: string
          label: Tokens
    target:
      type: boolean
      label: Open in new window
    icon:
      type: string
      label: Icon
    badge:
      type: mapping
      label: Badge
      mapping:
        type:
          type: string
          label: Badge Type

neo_toolbar_item.settings.link:
  type: neo_toolbar_item_link_settings

neo_toolbar_item.settings.link_local_tasks:
  type: neo_toolbar_item_link_settings

neo_toolbar_item.settings.region:
  type: neo_toolbar_item_settings
  mapping:
    url:
      type: string
      label: URL
    token:
      type: mapping
      label: Token
      mapping:
        tokens:
          type: string
          label: Tokens
    icon:
      type: string
      label: Icon

neo_toolbar_item.settings.create:
  type: neo_toolbar_item_settings
  mapping:
    icon:
      type: string
      label: Icon
    scheme:
      type: string
      label: Color Scheme
    node_enabled:
      type: boolean
      label: 'Enable content'
    node_bundles:
      type: sequence
      label: 'Content types'
      sequence:
        type: string
        label: 'Content type'
    node_exclude:
      type: boolean
      label: 'Exclude selected content types'
    taxonomy_enabled:
      type: boolean
      label: 'Enable taxonomy'
    taxonomy_bundles:
      type: sequence
      label: 'Taxonomy vocabularies'
      sequence:
        type: string
        label: 'Vocabulary'
    taxonomy_exclude:
      type: boolean
      label: 'Exclude selected vocabularies'
    media_enabled:
      type: boolean
      label: 'Enable media'
    media_bundles:
      type: sequence
      label: 'Media types'
      sequence:
        type: string
        label: 'Media type'
    media_exclude:
      type: boolean
      label: 'Exclude selected media types'
